import { AGENT_ROUTE } from "../constants.js";

export const INTENT_ID = {
  EMOTIONAL_SUPPORT: "emotional_support",
  DIETARY_ADVICE: "dietary_advice",
  EXERCISE_ADVICE: "exercise_advice",
  SLEEP_ADVICE: "sleep_advice",
  APP_FEATURE_EXPLANATION: "app_feature_explanation",
  CONTENT_RECOMMENDATION: "content_recommendation",
  DAILY_COMPANIONSHIP: "daily_companionship",
  HIGH_RISK_EXPRESSIONS: "high_risk_expressions",
  UNRECOGNIZED_AMBIGUOUS: "unrecognized_ambiguous",
};

export const INTENT_TAXONOMY = {
  [INTENT_ID.EMOTIONAL_SUPPORT]: {
    l2: ["anxiety_soothing", "emotion_regulation", "stress_release", "partner_support_communication"],
    preferredRoute: AGENT_ROUTE.EMOTIONAL_SUPPORT,
    mvpRoute: AGENT_ROUTE.EMOTIONAL_SUPPORT,
    topic: "general",
    requiresKb: false,
    requiresProfile: true,
    requiresSafety: true,
    strategySummary: "先共情与稳定，再给1-3条可执行动作，避免诊断化表达。",
  },
  [INTENT_ID.DIETARY_ADVICE]: {
    l2: ["meal_planning", "food_restriction", "nutrition_supplement", "safe_alternatives"],
    preferredRoute: "diet_agent",
    mvpRoute: AGENT_ROUTE.EMOTIONAL_SUPPORT,
    topic: "diet",
    requiresKb: true,
    requiresProfile: true,
    requiresSafety: true,
    strategySummary: "基于孕周和风险给饮食建议与禁忌，并提供替代方案。",
  },
  [INTENT_ID.EXERCISE_ADVICE]: {
    l2: ["exercise_feasibility", "intensity_plan", "post_exercise_discomfort", "frequency_arrangement"],
    preferredRoute: "exercise_agent",
    mvpRoute: AGENT_ROUTE.EMOTIONAL_SUPPORT,
    topic: "exercise",
    requiresKb: true,
    requiresProfile: true,
    requiresSafety: true,
    strategySummary: "先强调安全边界，再给低风险动作、停止条件与观察点。",
  },
  [INTENT_ID.SLEEP_ADVICE]: {
    l2: ["fall_asleep_difficulty", "night_waking", "schedule_optimization", "relaxation_routine"],
    preferredRoute: "sleep_agent",
    mvpRoute: AGENT_ROUTE.EMOTIONAL_SUPPORT,
    topic: "sleep",
    requiresKb: true,
    requiresProfile: true,
    requiresSafety: true,
    strategySummary: "给睡眠卫生与短流程干预，必要时建议线下专业评估。",
  },
  [INTENT_ID.APP_FEATURE_EXPLANATION]: {
    l2: ["feature_entry", "operation_steps", "setting_meaning", "data_explanation"],
    preferredRoute: AGENT_ROUTE.FEATURE_GUIDE,
    mvpRoute: AGENT_ROUTE.FEATURE_GUIDE,
    topic: "feature",
    requiresKb: false,
    requiresProfile: false,
    requiresSafety: true,
    strategySummary: "给点击级路径和常见错误修正，避免临床建议。",
  },
  [INTENT_ID.CONTENT_RECOMMENDATION]: {
    l2: ["article_recommendation", "course_recommendation", "week_based_recommendation", "state_based_recommendation"],
    preferredRoute: "content_recommend_agent",
    mvpRoute: AGENT_ROUTE.EMOTIONAL_SUPPORT,
    topic: "content",
    requiresKb: true,
    requiresProfile: true,
    requiresSafety: true,
    strategySummary: "按目标与状态分层推荐内容，给推荐理由和优先级。",
  },
  [INTENT_ID.DAILY_COMPANIONSHIP]: {
    l2: ["greeting", "light_chat", "companionship", "no_clear_task"],
    preferredRoute: AGENT_ROUTE.EMOTIONAL_SUPPORT,
    mvpRoute: AGENT_ROUTE.EMOTIONAL_SUPPORT,
    topic: "companionship",
    requiresKb: false,
    requiresProfile: false,
    requiresSafety: true,
    strategySummary: "轻陪伴+轻引导，控制轮次并引导到可执行小目标。",
  },
  [INTENT_ID.HIGH_RISK_EXPRESSIONS]: {
    l2: ["self_harm_expression", "suicide_expression", "severe_hopelessness", "emergency_signal"],
    preferredRoute: AGENT_ROUTE.RISK_ESCALATION,
    mvpRoute: AGENT_ROUTE.RISK_ESCALATION,
    topic: "risk",
    requiresKb: false,
    requiresProfile: false,
    requiresSafety: true,
    strategySummary: "立即中断常规安抚，输出升级动作、转介与紧急联系。",
  },
  [INTENT_ID.UNRECOGNIZED_AMBIGUOUS]: {
    l2: ["too_short", "multi_intent_mix", "insufficient_info", "semantic_unclear"],
    preferredRoute: "main_router_agent",
    mvpRoute: AGENT_ROUTE.EMOTIONAL_SUPPORT,
    topic: "general",
    requiresKb: false,
    requiresProfile: false,
    requiresSafety: true,
    strategySummary: "先澄清1轮，低置信度不做强结论，以安全兜底回复。",
  },
};

export function getIntentConfig(intentId) {
  return INTENT_TAXONOMY[intentId] || INTENT_TAXONOMY[INTENT_ID.UNRECOGNIZED_AMBIGUOUS];
}
